---
- hosts: '{{ target }}'
  remote_user: root

  tasks:

   - name: set static
     command: srv-config set system.network.interfaces.eth0.configure_ipv4 static

   - name: set ip
     command: srv-config set system.network.interfaces.eth0.ip_address 192.168.0.10

   - name: set subnet mask
     command: srv-config set system.network.interfaces.eth0.ip_netmask 255.255.255.0

   - name: apply settings
     command: srv-config apply


   - name: reboot server
     command: /sbin/shutdown -r +1
     async: 0
     poll: 0
     ignore_errors: true
